### ISSUE TITLE
Electron backend on Windows throws error

### ISSUE THREAD

**Issue by krcools** [spencerlyon2/PlotlyJS.jl#51]
When I try to plot on the command line through the Electron backend I get:

```
julia> using Plots

julia> plotlyjs()
Plots.PlotlyJSBackend()

julia> plot(1:10)
[Plots.jl] Initializing backend: plotlyjs
module.js:338
    throw err;
    ^

Error: Cannot find module 'app'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

    at Object.<anonymous> (C:\Users\ezzkc\.julia\v0.4\Blink\src\AtomShell\main.js:1:90)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

Plotting in Jupyter works as intended.

I did run `Blink.AtomShell.install()` as per manual instructions. I get the same error if I use `PlotlyJS` directly.

**Comment by krcools** [comment]
Ah, apparently this is fixed on `master`. Apologies...

**Comment by spencerlyon2** [comment]
Ok great, so can we close this issue?

I believe that master should match the latest release of PlotlyJS because I cut a release very recently.

**Comment by krcools** [comment]
Actually now I experience this on both master and the latest release. Could you keep this open for a bit longer? I will try to provide some more deterministic information...

**Comment by krcools** [comment]
OK, I get this message only when calling `PlotlyJS` from the `platformio-ide-terminal` plugin from `Atom`. The bug lies with them it seems. This issue can be closed. Sorry for wasting your time...
